name: ERPNext Test Runner

on:
  push:
    branches: [custom]
  pull_request:
    branches: [custom]

jobs:
  test-app:
    runs-on: ubuntu-latest
    name: Run Tests on hipl.local
    
    services:
      mariadb:
        image: mariadb:10.6
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Frappe Bench
        run: pip install frappe-bench

      - name: Initialize Test Environment
        run: |
          bench init --skip-redis-config-generation --python $(which python3) ~/frappe-bench
          mysql -h 127.0.0.1 -P 3306 -u root -proot -e "SET GLOBAL character_set_server = 'utf8mb4'"
          mysql -h 127.0.0.1 -P 3306 -u root -proot -e "SET GLOBAL collation_server = 'utf8mb4_unicode_ci'"

      - name: Install App and Test
        working-directory: ~/frappe-bench
        run: |
          bench get-app erpnext_mock_project $GITHUB_WORKSPACE
          bench new-site --db-root-password root --admin-password admin hipl.local
          bench --site hipl.local install-app erpnext_mock_project
          bench --site hipl.local set-config allow_tests true
          bench --site hipl.local run-tests --app erpnext_mock_project